game/urls.py
from django.urls import path, include

from .views import *

app_name = "game"

urlpatterns = [
    path('connect', connect, name='connect'),
    path('dashboard/<int:game_id>', dashboard, name='dashboard'),
    path('player_screen/<int:game_id>', player_screen, name='player_screen'),
]

tor/urls.py
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.views.static import serve

from tor import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('game/', include('game.urls', namespace='game'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

game/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _


class Game(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    code = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    balance = models.IntegerField(default=0)

    def __str__(self):
        """Возвращает строковое представление модели"""
        return self.code

    class Meta:
        verbose_name =_('Игра')
        verbose_name_plural = _('Игры')


class Player(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    balance = models.IntegerField()
    material = models.IntegerField(default=0)
    product = models.IntegerField(default=0)

    class Meta:
        unique_together = ("game", "user")
        verbose_name = _('Игрок')
        verbose_name_plural = _('Игроки')

    def __str__(self):
        """Возвращает строковое представление модели"""
        return self.user


class RoundStatus(models.Model):
    title = models.CharField(max_length=200, blank=True)
    code = models.CharField(max_length=10)


class Round(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    status = models.ForeignKey(RoundStatus, on_delete=models.CASCADE, blank=True, null=True)
    buy_minimal_materials = models.IntegerField(default=0, verbose_name='Минимальная стоимость покупки сырья')
    sell_max_goods = models.IntegerField(default=0, verbose_name='Максимальная стоимость продажи продукции')
    recycling = models.IntegerField(default=0, verbose_name='Переработка')
    store_materials = models.IntegerField(default=0, verbose_name='Хранение сырья')
    store_goods = models.IntegerField(default=0, verbose_name='Хранение продукции')
    tax = models.IntegerField(default=0, verbose_name='Налог')

    def __str__(self):
        """Возвращает строковое представление модели"""
        return self.id

    class Meta:
        verbose_name =_('Раунд')
        verbose_name_plural = _('Раунды')


class TransactionType(models.Model):
    title = models.CharField(max_length=200)
    code = models.CharField(max_length=10)

    def __str__(self):
        """Возвращает строковое представление модели"""
        return self.title

    class Meta:
        verbose_name =_('Тип операции')
        verbose_name_plural = _('Типы операций')


class Transaction(models.Model):
    type = models.ForeignKey(TransactionType, on_delete=models.CASCADE)
    price = models.IntegerField()
    count_materials = models.IntegerField()
    count_goods = models.IntegerField()

    def __str__(self):
        """Возвращает строковое представление модели"""
        return self.type

    class Meta:
        verbose_name =_('Операция')
        verbose_name_plural = _('Операции')


class MaterialBid(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    round = models.ForeignKey(Round, on_delete=models.CASCADE)
    count = models.IntegerField()
    price = models.IntegerField()

    def __str__(self):
        """Возвращает строковое представление модели"""
        return self.count, self.price

    class Meta:
        verbose_name =_('Ставка материалов')
        verbose_name_plural = _('Ставки матриалов')


class GoodsBid(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    round = models.ForeignKey(Round, on_delete=models.CASCADE)
    count = models.IntegerField()
    price = models.IntegerField()

    def __str__(self):
        """Возвращает строковое представление модели"""
        return self.code

    class Meta:
        verbose_name =_('Ставка продукции')
        verbose_name_plural = _('Ставки продукции')

game/forms.py
from django.forms import ModelForm
from .models import *


class ConnectForm(ModelForm):
    class Meta:
        model = Game
        fields = ['code']


class RoundForm(ModelForm):
    class Meta:
        model = Round
        fields = '__all__'


class Step1Form(ModelForm):
    class Meta:
        model = MaterialBid
        fields = '__all__'


class Step2Form(ModelForm):
    class Meta:
        model = TransactionType
        fields = '__all__'


class Step3Form(ModelForm):
    class Meta:
        model = GoodsBid
        fields = '__all__'

game/views.py
# from curtsies.events import get_key
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST

from .models import *
from .forms import *
from django.shortcuts import redirect


@login_required
def connect(request):
    """Если введен корректный номер игры, перекидывает на dashboard"""
    game = Game.objects.filter(code=request.POST.get('code')).last()

    if game:
        player = Player.objects.create(
            game=game,
            user=request.user,
            balance=game.balance
        )
        return HttpResponseRedirect('game/player_screen/' + str(game.id))
    else:
        return render(request, 'game/connect.html')



# TODO имеет доступ только владелец игры

@login_required
def dashboard(request, game_id):
    """Лобби"""
    if request.user == User.objects.get(username='admin'):
        if request.method == 'POST':
            round = Round.objects.get(id=request.POST.get('id'))
            if round.status == 'step1':
                # TODO Перевести на шаг2. Посчитать лучшие предложения от игроков по закупке сырья(т.е. максимальная сумма)
                """Допустим есть 20 ед сырья и 3 игрока, которые не видят ставки друг друга. Первый предложил купить 5ед за 1000Р каждая,
                второй 10 по 1500, третий 15 по 2000. Нужно выбрать максимальную цену(3й игрок и по ней продать все сырье
                которое он запросил, далее у второго игрока оставшееся(5 получается), а первому не остается ничего). В процессе отображать изменения баланса и кол-ва сырья"""
                # TODO Проверить логику
                price_list_user = {} #словарь для извлечения юзеров с наибольшей ценой
                price_list = [] #список из сумм, которые готовы предложить
                for user in MaterialBid.objects.all(): # добавляем юзеров и их предложенную сумму
                    user_name = user.user.username
                    price = user.price
                    count = user.count
                    total_price = price * count
                    price_list_user[user_name] = total_price
                    price_list.append(total_price)
                price_list.sort()
                price_list.reverse()


                for i in range(len(price_list)):  # вычитаем у всех балансы
                    player = get_key(price_list_user, i)  # тут извлекаем игрока
                    get_player = MaterialBid.objects.get(user=player)
                    round_result = Game.objects.get(id=game_id).balance
                    player_balance = Player.objects.get(user_name=player).balance
                    player_material = Player.objects.get(user_name=player).material
                    round_result = int(round_result) - int(get_player.count)

                    if round_result != -1 | round_result == 0:
                        Game.objects.get(id=game_id).balance = round_result
                        Player.objects.get(user_name=player).balance = int(player_balance) - int(get_player.price * get_player.count)
                        Player.objects.get(user_name=player).material = int(get_player.count) + int(player_material)

                    elif round_result < 0 & round_result != -1:
                        Player.objects.get(user_name=player).balance = int(player_balance) - int(get_player.price * get_player.count)
                        Player.objects.get(user_name=player).material = int(get_player.count) + int(round_result)
                        Game.objects.get(id=game_id).balance = -1
                round.status = RoundStatus.objects.get(code='step2')
            elif round.status == 'step2':
                # TODO Перевести на шаг3. Переработать сырье в продукцию.
                pass
            elif round.status == 'step3':
                # TODO Перевести на шаг4. Реализация продукции. Посчитать лучшее(минимальное по стоимости) предложение о продаже продукции. Занести все в транзакции.
                pass
            elif round.status == 'step4':
                # TODO Завершить раунд. Вычесть стоимость хранения и налоги.
                pass

        game = Game.objects.get_or_404(id = game_id)
        players_list = Player.objects.filter(game = game)
        rounds_list = Round.objects.filter(game=game)
        last_round = rounds_list.filter(is_active =True).last()
        context = {
            'players_list': players_list,
            'rounds_list': rounds_list,
            'last_round': last_round
        }
        return render(request, 'game/dashboard.html', {})
    else:
        game = Game.objects.filter(code=request.POST.get('code')).last()
        return HttpResponseRedirect('game/player_screen/' + str(game.id))


# имеет доступ только игрок игры
@login_required
def player_screen(request, game_id):
    transaction_types = TransactionType.objects.all()
    pass

# Должна создать раунд и редирект на дашборд
@require_POST
def create_round(request, game_id):
    """Принимает начальные данные и запускает раунд"""
    # Отправлены данные POST; обработать данные
    form = RoundForm(request.POST)
    if form.is_valid():
        new_round = form.save(commit=False)
        new_round.game_id = game_id
        new_round.save()
        return HttpResponseRedirect('game/dashboard.html', args=[game_id])


# TODO смотри Схема.jpg


@require_POST
def player_step1(request, round_id):
    """Заполняет форму по количеству и стоимости покупки сырья"""
    form = Step1Form(request.POST)
    if form.is_valid():
        step1 = form.save()
        step1.round_id = round_id
        step1.save()
        return HttpResponseRedirect('game/dashboard.html', args=[round_id])


@require_POST
def player_step2(request, round_id):
    """Заполняет форму по кол-ву переработки сырья в продукцию"""
    form = Step2Form(request.POST)
    if form.is_valid():
        step2 = form.save()
        step2.round_id = round_id
        step2.save()
        return HttpResponseRedirect('game/dashboard.html', args=[round_id])


@require_POST
def player_step3(request, round_id):
    """Заполняет форму по продаже продукции и стоимости"""
    form = Step3Form(request.POST)
    if form.is_valid():
        step3 = form.save()
        step3.round_id = round_id
        step3.save()
        return HttpResponseRedirect('game/dashboard.html', args=[round_id])

templates/game/connect.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row pt-5">
            <div class="col-md-5 col-1"></div>
            <div class="col-md-2 col-12 text-center">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_code">Введите код игры</label>
                        <input type="text" name="code" class="form-control" id="id_code" placeholder="Пример: XHWLGW"
                               maxlength="6" style="text-transform:uppercase">
                    </div>
                    <button type="submit" class="btn btn-primary">Войти</button>
                </form>
            </div>
            <div class="col-md-5 col-1"></div>
        </div>
    </div>s
{% endblock %}

templates/game/dashboard.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row pt-5">
            <!-- Список игроков -->
            <div class="col-12 pb-4">
                <h3>Игроки</h3>
                <table class="table">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Игрок</th>
                        <th>Баланс, руб.</th>
                        <th>Материалы, шт.</th>
                        <th>Продукция, шт.</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for player in players %}
                    <tr>
                        <th scope="row">{{ player.id }}</th>
                        <td>{{ player.user }}</td>
                        <td>{{ player.balance }}</td>
                        <td>{{ player.material }}</td>
                        <td>{{ player.product }}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            {% if user.is_superuser or user.is_staff %}
                <div class="col-md-4 col-12">
                    <form action="">
                        {% if not round %}
                        <div class="form-group">
                            <label for="formGroupExampleInput">Количество реализуемого сырья</label>
                            <input type="text" class="form-control" id="formGroupExampleInput" value="20">
                        </div>
                        <div class="form-group">
                            <label for="formGroupExampleInput">Количество покупаемой продукции</label>
                            <input type="text" class="form-control" id="formGroupExampleInput" value="20" >
                        </div>
                        <div class="form-group">
                            <label for="formGroupExampleInput">Минимальная стоимость покупки сырья</label>
                            <input type="text" class="form-control" id="formGroupExampleInput" value="1000" >
                        </div>
                        <div class="form-group">
                            <label for="formGroupExampleInput">Максимальная стоимость продажи продукции</label>
                            <input type="text" class="form-control" id="formGroupExampleInput" value="10000" >
                        </div>
                        <div class="form-group">
                            <label for="formGroupExampleInput">Стоимость переработки сырья в продукцию</label>
                            <input type="text" class="form-control" id="formGroupExampleInput" value="500" >
                        </div>
                        <div class="form-group">
                            <label for="formGroupExampleInput">Стоимость хранения сырья</label>
                            <input type="text" class="form-control" id="formGroupExampleInput" value="500" >
                        </div>
                        <div class="form-group">
                            <label for="formGroupExampleInput">Стоимость хранения продукции</label>
                            <input type="text" class="form-control" id="formGroupExampleInput" value="1000" >
                        </div>
                        <div class="form-group">
                            <label for="formGroupExampleInput">Налог</label>
                            <input type="text" class="form-control" id="formGroupExampleInput" value="1000" >
                        </div>
                        <button type="submit" class="btn btn-primary">Начать раунд</button>
                        {% else %}
                            <p>Данные по раунду:</p>
                            <p>{{ round.id }}</p>
                            <p>{{ round.buy_minimal_materials }}</p>
                            <p>{{ round.sell_max_goods }}</p>
                            {% if round.status == 'step1' %}
                            <input type="text" name="id" value="{{ round.id }}" hidden>
                            <button type="submit" class="btn btn-primary">Перейти на шаг2</button>
                            {% elif round.status == 'step2' %}
                            <input type="text" name="id" value="{{ round.id }}" hidden>
                            <button type="submit" class="btn btn-primary">Перейти на шаг3</button>
                            {% elif round.status == 'step3' %}
                            <input type="text" name="id" value="{{ round.id }}" hidden>
                            <button type="submit" class="btn btn-primary">Завершить раунд</button>
                            {% endif %}
                        {% endif %}
                    </form>
                </div>
            {% endif %}
            <div class="col-md-8 col-12">
                <h3>Раунды</h3>
                <table class="table">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Кол-во сырья</th>
                        <th>Кол-во продукции</th>
                        <th>Покупка сырья</th>
                        <th>Продажа продукции</th>
                        <th>Переработка</th>
                        <th>Хранение сырья</th>
                        <th>Хранение продукции</th>
                        <th>Налог</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for round in rounds %}
                    <tr>
                        <th scope="row">{{ round.id }}</th>
                        <td>{{ transaction_type.count_materials }}</td>
                        <td>{{ transaction_type.count_goods }}</td>
                        <td>{{ round.buy_minimal_materials }}</td>
                        <td>{{ round.sell_max_goods }}</td>
                        <td>{{ round.recycling }}</td>
                        <td>{{ round.store_materials }}</td>
                        <td>{{ round.store_goods }}</td>
                        <td>{{ round.tax }}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

        </div>
    </div>
{% endblock %}

templates/game/player_screen.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row pt-5">
            <!-- Список игроков -->
            <div class="col-12 pb-4">
                <h3>Игроки</h3>
                <table class="table">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Игрок</th>
                        <th>Баланс, руб.</th>
                        <th>Материалы, шт.</th>
                        <th>Продукция, шт.</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for player in players %}
                    <tr>
                        <th scope="row">{{ player.id }}</th>
                        <td>{{ player.user }}</td>
                        <td>{{ player.balance }}</td>
                        <td>{{ player.material }}</td>
                        <td>{{ player.product }}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-md-4 col-12">
                    <form action="">
                        {% if not round %}
                        <div class="form-group">
                            <label for="formGroupExampleInput">Количество реализуемого сырья</label>
                            <input type="text" name="count_materials" class="form-control" id="formGroupExampleInput" value="20">
                        </div>
                        <div class="form-group">
                            <label for="formGroupExampleInput">Количество покупаемой продукции</label>
                            <input type="text" name="count_goods" class="form-control" id="formGroupExampleInput" value="20" >
                        </div>
                        <div class="form-group">
                            <label for="formGroupExampleInput">Минимальная стоимость покупки сырья</label>
                            <input type="text" name="buy_minimal_materials" class="form-control" id="formGroupExampleInput" value="1000" >
                        </div>
                        <div class="form-group">
                            <label for="formGroupExampleInput">Максимальная стоимость продажи продукции</label>
                            <input type="text" name="sell_max_goods" class="form-control" id="formGroupExampleInput" value="10000" >
                        </div>
                        <div class="form-group">
                            <label for="formGroupExampleInput">Стоимость переработки сырья в продукцию</label>
                            <input type="text" name="recycling" class="form-control" id="formGroupExampleInput" value="500" >
                        </div>
                        <div class="form-group">
                            <label for="formGroupExampleInput">Стоимость хранения сырья</label>
                            <input type="text" name="store_materials" class="form-control" id="formGroupExampleInput" value="500" >
                        </div>
                        <div class="form-group">
                            <label for="formGroupExampleInput">Стоимость хранения продукции</label>
                            <input type="text" name="store_goods" class="form-control" id="formGroupExampleInput" value="1000" >
                        </div>
                        <div class="form-group">
                            <label for="formGroupExampleInput">Налог</label>
                            <input type="text" name="tax" class="form-control" id="formGroupExampleInput" value="1000" >
                        </div>
                        <button type="submit" class="btn btn-primary">Начать раунд</button>
                        {% else %}
                            <p>Данные по раунду:</p>
                            <p>{{ round.id }}</p>
                            <p>{{ round.buy_minimal_materials }}</p>
                            <p>{{ round.sell_max_goods }}</p>
                            {% if round.status == 'step1' %}
                            <input type="text" name="id" value="{{ round.id }}" hidden>
                            <button type="submit" class="btn btn-primary">Перейти на шаг2</button>
                            {% elif round.status == 'step2' %}
                            <input type="text" name="id" value="{{ round.id }}" hidden>
                            <button type="submit" class="btn btn-primary">Перейти на шаг3</button>
                            {% elif round.status == 'step3' %}
                            <input type="text" name="id" value="{{ round.id }}" hidden>
                            <button type="submit" class="btn btn-primary">Завершить раунд</button>
                            {% endif %}
                        {% endif %}
                    </form>
                </div>
            <div class="col-md-8 col-12">
                <h3>Раунды</h3>
                <table class="table">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Кол-во сырья</th>
                        <th>Кол-во продукции</th>
                        <th>Покупка сырья</th>
                        <th>Продажа продукции</th>
                        <th>Переработка</th>
                        <th>Хранение сырья</th>
                        <th>Хранение продукции</th>
                        <th>Налог</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for round in rounds %}
                    <tr>
                        <th scope="row">{{ round.id }}</th>
                        <td>{{ transaction_type.count_materials }}</td>
                        <td>{{ transaction_type.count_goods }}</td>
                        <td>{{ round.buy_minimal_materials }}</td>
                        <td>{{ round.sell_max_goods }}</td>
                        <td>{{ round.recycling }}</td>
                        <td>{{ round.store_materials }}</td>
                        <td>{{ round.store_goods }}</td>
                        <td>{{ round.tax }}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

        </div>
    </div>
{% endblock %}